version: 1.55.2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gosec
    - gocritic
    - gocyclo
    - goimports
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
  disable:
    - golint  # deprecated
