linters:
  enable:
    - gofmt
    - govet
    - golint
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - unconvert
    - goconst
    - gocyclo
    - goimports
    - misspell
    - unparam
    - prealloc

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor/
    - testdata/

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US 