apiVersion: v1
kind: ServiceAccount
metadata:
  name: sqlextract
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sqlextract-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sqlextract-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: sqlextract
  namespace: default
roleRef:
  kind: Role
  name: sqlextract-role
  apiGroup: rbac.authorization.k8s.io 